apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: harbor.xxx.com/ygjpro/mamba
  newName: harbor.xxx.com/ygjpro/mamba
  newTag: "202011291143"
namespace: canary
#- affinity_patch.yaml
patchesStrategicMerge:
- volumes_patch.yaml

transformers:
# - metadataLabelTransformer.yaml
- labels.yaml
