apiVersion: apps/v1
kind: Deployment
metadata:
 name: stable-mamba
spec:
  template:
    spec:
      volumes:
        - name: "mambafile"
          persistentVolumeClaim:
            claimName: mambafile